// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpmuZfgHQp_v49G_LJ-TLPKHEXUlvzrN0',
    appId: '1:733984476301:web:4116addf46715d8e9d66c4',
    messagingSenderId: '733984476301',
    projectId: 'instagram-clone-f5ba5',
    authDomain: 'instagram-clone-f5ba5.firebaseapp.com',
    storageBucket: 'instagram-clone-f5ba5.appspot.com',
    measurementId: 'G-WBC1WD7M3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClP2rOIHmGjw62COIkPwziYGF0toSj53w',
    appId: '1:733984476301:android:a143d0e9541772159d66c4',
    messagingSenderId: '733984476301',
    projectId: 'instagram-clone-f5ba5',
    storageBucket: 'instagram-clone-f5ba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxL5593SiLz5A7qaqsArI-b8PBogfXsFY',
    appId: '1:733984476301:ios:1d34655fc969f1b39d66c4',
    messagingSenderId: '733984476301',
    projectId: 'instagram-clone-f5ba5',
    storageBucket: 'instagram-clone-f5ba5.appspot.com',
    iosClientId: '733984476301-l7tout31rcoq7njrimrk37s8bbndluds.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxL5593SiLz5A7qaqsArI-b8PBogfXsFY',
    appId: '1:733984476301:ios:1d34655fc969f1b39d66c4',
    messagingSenderId: '733984476301',
    projectId: 'instagram-clone-f5ba5',
    storageBucket: 'instagram-clone-f5ba5.appspot.com',
    iosClientId: '733984476301-l7tout31rcoq7njrimrk37s8bbndluds.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
